### ISSUE TITLE
Bottom right info (clock, username, ...) does not appear

### ISSUE THREAD

**Issue by oskargirardin** [adriankarlen/bar.wezterm#19]
Hello !

I used the code you provided in the `README.md` file, but unfortunately the bottom right modules do not appear. Do you know how to fix this ? I am on Mac OS.

My code inside of `.wezterm.lua`:
```lua
-- Tab bar
config.use_fancy_tab_bar = true

local bar = wezterm.plugin.require("https://github.com/adriankarlen/bar.wezterm")
bar.apply_to_config(
	config,
	{
		modules = {
			tabs = {
				active_tab_fg = 3,
      	                        inactive_tab_fg = 5,
			}
		}
	}
)
```

My wezterm window:

![Screenshot 2024-09-23 at 15 23 01](https://github.com/user-attachments/assets/3ec78fa7-7abc-4a05-9004-97cc3f38fcd9)

Thanks !
Oskar

**Comment by adriankarlen** [comment]
I am unable to recreate this issue, if you open the debug overview do you have any errors being thrown?

**Comment by rockthedwaynezhou** [comment]
I was having the same issue, disabling the Spotify widget fixed it, this was the error that was being thrown in the Debug view:

```
ERROR wezterm_gui::termwindow > while processing update-status event: No such file or directory (os error 2)
stack traceback:
        [C]: in local 'poll'
        [string "?"]:4: in function 'wezterm.run_child_process'
        ...omsZsadriankarlensZsbarsDswezterm/plugin/bar/spotify.lua:33: in function 'bar.spotify.get_currently_playing'
        (...tail calls...)
        ...hubsDscomsZsadriankarlensZsbarsDswezterm/plugin/init.lua:187: in function <...hubsDscomsZsadriankarlensZsbarsDswezterm/plugin/init.lua:105>
```

**Comment by adriankarlen** [comment]
I'll just have spotify disabled by default then, hopefully this resolves the issue.

**Comment by oskargirardin** [comment]
Yes this resolved it. Thank you both !
