### ISSUE TITLE
Add padding as an option ?

### ISSUE THREAD

**Issue by oskargirardin** [adriankarlen/bar.wezterm#24]
When I disable the panes and workspace items, there is not enough padding on the left. There is more padding on the right where the clock is. Is there a possibility to add padding to the left as an option ?

![image](https://github.com/user-attachments/assets/2fb701f8-5a9a-4f6a-ac63-6e19b5af9737)
 
Thanks !
Oskar

**Comment by adriankarlen** [comment]
Yes, that could be an idea, I've also noticed that the right group adds a separator on the last item, which it should not. Will investigate how this can be added in an intuitive way.
