### ISSUE TITLE
Plugin crashes if no color scheme is defined

### ISSUE THREAD

**Issue by itsdeadguy** [adriankarlen/bar.wezterm#26]
I've been trying to test this bar as it looks pretty nice, but it chokes on my config which uses the default colorscheme and thus is not explicitly set on the config file. My config file only has a handful of keybindings and the call to your plugin.

Could something be done about this or should i set a colorscheme manually? i don't know what the default is called.

Here's the error
```
runtime error: ...hubsDscomsZsadriankarlensZsbarsDswezterm/plugin/init.lua:55:
attempt to index a nil value (local 'scheme')
```

**Comment by adriankarlen** [comment]
Hi, thanks for reaching out, I was able to reproduce this. It has worked previously with the default scheme, perhaps I've introduced some bug to this along the way. Thanks for reporting.

**Comment by adriankarlen** [comment]
This issue is now resolved, thanks for pointing it out!
