### ISSUE TITLE
Allow user to change top and bottom padding

### ISSUE THREAD

**Issue by DeeGeeMan** [adriankarlen/bar.wezterm#29]
I need to add additional padding to the top and bottom of the status bar, but the only options are `padding.left` and `padding.right`.

Example:
```
bar.apply_to_config(config, {
	position = "bottom",
	padding = {
                top = 5,
                bottom = 5,
		left = 1,
		right = 1,
	},
	...
})

```

**Comment by adriankarlen** [comment]
Hi, Unfortunately this is not possible to do, the tab bar is one cell high. If you want it to be larger, you can increase it's font size. 

Relevant wezterm links:
- https://github.com/wez/wezterm/discussions/2936
- https://github.com/wez/wezterm/issues/3789
