### ISSUE TITLE
Get rid of the right arrow

### ISSUE THREAD

**Issue by suinming** [adriankarlen/bar.wezterm#31]
![image](https://github.com/user-attachments/assets/3b44a18e-5f53-4a43-aaef-dfe73a5be4b3)
In the wezterm config, I try to set nil in the separator but it do not get rid of the right arrow in the tab bar. What is the correct way to disable the arrow?
```lua
local bar = wezterm.plugin.require("https://github.com/adriankarlen/bar.wezterm")
bar.apply_to_config(
  config,
  {
    position = "top",
    separator = {
      space = 2,
      left_icon = nil,
      right_icon = nil,
      field_icon = nil
    }
)
```

**Comment by adriankarlen** [comment]
When passing nil as an option the config merge will use the default value, as it is the same as not passing it, simply pass empty string to remove the icon.
